### ISSUE TITLE
Build monitor view not embeddable

### ISSUE THREAD

**Issue by nafmo** [jenkinsci/build-monitor-plugin#110]
I am trying to bembed the build monitor view in another page, but I am unable to as the document is served with a header denying it:

X-Frame-Options: sameorigin

**Comment by nafmo** [comment]
I added -Djenkins.security.FrameOptionsPageDecorator.enabled=false to the command line to work around this. Would be nice to have this as a setting in the UI, though.

**Comment by boughtonp** [comment]
Using the XFrame Filter Plugin is not enough to make Build Monitor embeddable.

It attempts to load the page (the background and logo appears), but then it just starts flashing and reloading, the console filling with:

	POST http://<intranet>/$stapler/bound/<uuid>/fetchJobViews 404 (Not Found)
	XHR finished loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".
	XHR failed loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".

	POST http://<intranet>/$stapler/bound/<uuid>/fetchJobViews 404 (Not Found)
	XHR finished loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".
	XHR failed loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".

	POST http://<intranet>/$stapler/bound/<uuid>/fetchJobViews 404 (Not Found)
	XHR finished loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".
	XHR failed loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".

	POST http://<intranet>/$stapler/bound/<uuid>/fetchJobViews 404 (Not Found)
	XHR finished loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".
	XHR failed loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".

	POST http://<intranet>/$stapler/bound/<uuid>/fetchJobViews 404 (Not Found)
	XHR finished loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".
	XHR failed loading: POST "http://<intranet>/$stapler/bound/<uuid>/fetchJobViews".

All pointing at angular-1.1.5.min.js:106

To reproduce:
* Install XFrameOptions, configure to send blank header (or appropriate value).
* Use this sample HTML: `<!doctype html ><iframe src="http://jenkins/view/Build%20Status" />`

**Comment by boughtonp** [comment]
Seems to be related to #166
