### ISSUE TITLE
Colorblind Palette?

### ISSUE THREAD

**Issue by xpucadad** [jenkinsci/build-monitor-plugin#30]
I would like to have a color palette that makes it easier (possible?) for color blind folks to see the various details communicated via color in the plugin.

Thanks.

Ken

**Comment by lam2558** [comment]
Is there a way to set the default setting for font size and columns ?

**Comment by jan-molak** [comment]
@lam2558 - not yet, but that would make an awesome pull request! :) #119 suggests a way this could be implemented.

**Comment by lam2558** [comment]
Awesome!

**Comment by manurFR** [comment]
Thanks a lot for this !

**Comment by jan-molak** [comment]
@manurFR - no worries, hope it helps! I wasn't sure if this set of patterns/colours makes sense for the colour-blind so feedback is much appreciated!
