### ISSUE TITLE
Order is not retained through JCasC

### ISSUE THREAD

**Issue by Enrice** [jenkinsci/build-monitor-plugin#491]
It seems the only field that cannot be persisted in the jenkins.yaml is "Ordered by".

Please fix!

**Comment by Enrice** [comment]
Maybe it's just because some fields are not exported through JCasC:
`  buildMonitorView:
    permissionToCollectAnonymousUsageStatistics: true
`

**Comment by Enrice** [comment]
Now also the max. number of columns is also not retained.
After each restart I have to manually fix this - annoying.

**Comment by HugoSilvaSantos** [comment]
Hi,

Any updates regarding this issue? 
I have a couple of dashboards in my Jenkins setup. Having the property "Ordered by" defined as code would save me a lot of time. After a Jenkins restart, that specific property needs to be manually defined in Jenkin's Web UI.

BR, Hugo

**Comment by Enrice** [comment]
Thanks!
