### ISSUE TITLE
Migration to Jenkins CI Org and New Maintainers

### ISSUE THREAD

**Issue by jan-molak** [jenkinsci/build-monitor-plugin#656]
:wave: Hello!

I started Jenkins Build Monitor on June 9th, 2013. This was 10 years ago.

Build Monitor was the first project I published on GitHub. However, it turned out to be only the beginning of my journey with open-source development. Since then, I have created many other open-source projects, the most notable of which is [Serenity/JS](https://github.com/serenity-js).

Even though I created Build Monitor to help just a handful of teams I was working with at the time to keep our builds green, Build Monitor now became part of the essential set of plugins running on thousands of Jenkins CI servers all over the world. 

As such, it needs to continue to evolve and support development teams who rely on it every day.

It is my pleasure to announce that I've agreed with Jenkins CI Maintainers to incorporate Build Monitor into Jenkins CI org on GitHub and for them to take over the maintenance of the project.

I believe that with their stewardship, Build Monitor will continue to receive the care it needs and help you and your team continuously deliver working software.

All the best,
Jan Molak

**Comment by basil** [comment]
[Build Monitor View](https://plugins.jenkins.io/build-monitor-plugin/) is now [hosted in the jenkinsci GitHub organization](https://github.com/jenkinsci/build-monitor-plugin), [built on ci.jenkins.io](https://ci.jenkins.io/job/Plugins/job/build-monitor-plugin/job/master/), and deployed with our standard CD process.
