### ISSUE TITLE
Auto build for newly created feature branch

### ISSUE THREAD

**Issue by ericoliveros** [jenkinsci/build-monitor-plugin#741]
### What feature do you want to see added?

Auto build for newly created feature branch, this will be a good help when doing a pull request because we can assure that latest code changes are buildable.

**Comment by dcendents** [comment]
Hi @ericoliveros , you want new branches to be added automatically to the build monitor view or you want the new branch to be built automatically?

The former can be done if you use a regular expression to include jobs in the view or you can use the View Job Filters plugin.

The latter is not a functionality of a view, you need to configure that in the job itself.

**Comment by dcendents** [comment]
there isn't a single way to do it, normally new jobs are built automatically and then it depends on your configuration.

I'd check the documentation of the plugin you use to fetch your code from your source code repository.

for example:

https://plugins.jenkins.io/github-branch-source/
https://plugins.jenkins.io/gitlab-branch-source/
