### ISSUE TITLE
Support environments without access to the Internet

### ISSUE THREAD

**Issue by jaranflaath** [jenkinsci/build-monitor-plugin#8]
Hi, 

we have our Jenkins server running in an environment without access to the internet. Would it be possible to have a version of the build monitor plugin that does not require internet access, but have all required resources bundled with the plugin?

**Comment by shivanshi-tyagi** [comment]
Hi,
I have installed Jenkins and plugins on a machine that does not has internet access. Can you please tell me how can I use Jenkins without using Git ?
