### ISSUE TITLE
Remove YUI from build-monitor

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/build-monitor-plugin#968]
### What feature do you want to see added?

The plugin uses YAHOO.util.Cookie

https://github.com/jenkinsci/build-monitor-plugin/blob/503b188bb84c174fe7bab4b335c21807ca412061/build-monitor-plugin/src/main/webapp/scripts/services.js#L6

https://github.com/jenkinsci/build-monitor-plugin/blob/503b188bb84c174fe7bab4b335c21807ca412061/build-monitor-plugin/src/test/javascript/unit/services/cookieJarSpec.js#L8

https://github.com/jenkinsci/build-monitor-plugin/blob/e39e949138025fac3fdbdb6e18c4716196d636da/build-monitor-plugin/src/main/resources/com/smartcodeltd/jenkinsci/plugins/buildmonitor/BuildMonitorView/index.jelly#L30

To be able to stop delivering YUI which is no longer maintained all plugins should stop using it.

See https://issues.jenkins.io/browse/JENKINS-73539

The plugin should directly read/write cookies with plain javascript probably.

**Comment by zbynek** [comment]
Since these cookies do not seem to be read by the server, storing in LocalStorage might be better.
